### ISSUE TITLE
Local Repo info not available

### ISSUE THREAD

**Issue by narendranss** [khmarbaise/jdk9-jlink-jmod-example#1]
hi, I see local repo path in your pom.xml file. The project has no details of setting them up. Can you provide more info on it?
maven-jlink-plugin and maven-jmod-plugin are they going to get official support? If so when we can anticipate them to be available in public maven repository?

**Comment by khmarbaise** [comment]
The local repo path in those examples are just there. They are not really needed to run the example....

**Comment by khmarbaise** [comment]
The plugins are available via https://repository.apache.org/content/groups/snapshots/ (as SNAPSHOT versions.
